import { parseDsn, type DsnResult } from "./parse-dsn";

/**
 * Inbound classification.
 *
 * This is the rule that makes multi-step sequences safe to run. Most of Paul's
 * recipients are `support@` addresses sitting behind Zendesk or Gorgias, so an
 * inbound message is far more likely to be a ticket acknowledgement than a
 * human. Treating every inbound message as a reply would silently kill most
 * sequences after step 1; treating none of them as one would email people who
 * already answered.
 *
 * Order matters. A bounce can look like a reply (it quotes the original), and
 * an auto-reply can contain the word "unsubscribe" in a footer, so the checks
 * run most-specific first.
 */

export type InboundClassification =
  | "bounce"
  | "auto_reply"
  | "unsubscribe"
  | "reply";

export interface InboundHeaders {
  from: string;
  to?: string | null;
  subject?: string | null;
  messageId?: string | null;
  inReplyTo?: string | null;
  /** Already split on whitespace by the caller. */
  references?: string[];
  contentType?: string | null;
  returnPath?: string | null;
  autoSubmitted?: string | null;
  precedence?: string | null;
  listId?: string | null;
  listUnsubscribe?: string | null;
  xAutoreply?: string | null;
  xAutorespond?: string | null;
  xAutoResponseSuppress?: string | null;
  xFailedRecipients?: string | null;
}

export interface InboundMessage {
  headers: InboundHeaders;
  /** Plain text body. */
  text: string;
  /** Full raw source, used to dig a DSN out of its attached report part. */
  raw?: string;
}

export interface ClassificationResult {
  classification: InboundClassification;
  /** Why it was classified this way, for the inbox UI and for debugging. */
  reason: string;
  /** Present when the classification is "bounce". */
  dsn?: DsnResult;
  /** Address to suppress, for bounce and unsubscribe. */
  suppress?: string;
}

const MAILER_DAEMON =
  /(^|[<\s])(mailer-daemon|postmaster|no-?reply@.*(mail|smtp|mx)|bounce[s]?)@/i;

const BOUNCE_SUBJECT =
  /(undeliverable|delivery status notification|delivery failure|returned mail|mail delivery (failed|subsystem)|failure notice|message could not be delivered)/i;

const AUTOREPLY_SUBJECT =
  /(out of (the )?office|auto(matic)?[- ]?reply|autoreply|away from (my|the) (desk|office)|vacation reply|thanks for (contacting|reaching out|your (message|email|enquiry|inquiry)))/i;

/** Helpdesk acknowledgements. These are bots, whatever the subject says. */
const TICKET_MARKERS =
  /(we('| ha)ve received your (message|request|email)|your (ticket|request|case) (has been|was) (created|received|opened)|ticket #?\d+|case #?\d+|reference #?\d+|this is an automated (response|message|confirmation))/i;

const UNSUBSCRIBE_PHRASES = [
  "unsubscribe",
  "remove me from your list",
  "remove me from this list",
  "take me off your list",
  "stop emailing me",
  "stop contacting me",
  "do not contact me",
  "don't contact me",
  "do not email me",
  "don't email me",
  "opt me out",
  "no longer wish to receive",
  "please remove me",
];

/**
 * Strip quoted history so a phrase in Paul's own footer is not read as the
 * recipient's intent. Handles `>` quoting and the common client separators.
 */
export function unquotedText(text: string): string {
  const lines = text.split(/\r?\n/);
  const kept: string[] = [];

  for (const line of lines) {
    const trimmed = line.trim();
    if (trimmed.startsWith(">")) continue;
    if (/^on .+ wrote:$/i.test(trimmed)) break;
    if (/^-{2,}\s*original message\s*-{2,}$/i.test(trimmed)) break;
    if (/^_{5,}$/.test(trimmed)) break;
    if (/^from:\s/i.test(trimmed) && kept.length > 0) break;
    kept.push(line);
  }

  return kept.join("\n");
}

function headerPresent(value: string | null | undefined): boolean {
  return typeof value === "string" && value.trim().length > 0;
}

function looksLikeBounce(message: InboundMessage): boolean {
  const { headers } = message;

  if (/report-type=["']?delivery-status/i.test(headers.contentType ?? "")) return true;
  if (headerPresent(headers.xFailedRecipients)) return true;

  // A null Return-Path is the RFC 5321 marker for a notification that must not
  // itself be bounced, which in practice means a DSN.
  if (headers.returnPath?.trim() === "<>") return true;

  if (MAILER_DAEMON.test(headers.from)) return true;
  if (BOUNCE_SUBJECT.test(headers.subject ?? "")) return true;

  return false;
}

function looksLikeAutoReply(message: InboundMessage): boolean {
  const { headers } = message;

  // RFC 3834. Any value other than "no" means generated by an automaton.
  const autoSubmitted = headers.autoSubmitted?.trim().toLowerCase();
  if (autoSubmitted && autoSubmitted !== "no") return true;

  if (headerPresent(headers.xAutoreply)) return true;
  if (headerPresent(headers.xAutorespond)) return true;
  if (headerPresent(headers.xAutoResponseSuppress)) return true;
  if (headerPresent(headers.listId)) return true;

  const precedence = headers.precedence?.trim().toLowerCase();
  if (precedence && ["bulk", "junk", "list", "auto_reply"].includes(precedence)) {
    return true;
  }

  if (AUTOREPLY_SUBJECT.test(headers.subject ?? "")) return true;
  if (TICKET_MARKERS.test(unquotedText(message.text))) return true;

  return false;
}

/**
 * A curt one-word refusal.
 *
 * The footer asks people to reply with "stop", and that is what they send:
 * "stop", "Stop.", "no thanks", "remove". None of those contain a phrase from
 * the list above, and missing one means continuing to email somebody who
 * plainly said no. Length-bounded so a real reply that happens to use the word
 * ("we had to stop taking cards in March") is not caught.
 */
const CURT_REFUSAL = /^\W*(stop|unsubscribe|remove|no|no thanks|not interested|opt out)\W*$/i;
const CURT_REFUSAL_MAX_CHARS = 40;

function findUnsubscribeIntent(message: InboundMessage): string | null {
  const unquoted = unquotedText(message.text).trim();
  const body = unquoted.toLowerCase();

  for (const phrase of UNSUBSCRIBE_PHRASES) {
    if (body.includes(phrase)) return phrase;
  }

  if (unquoted.length <= CURT_REFUSAL_MAX_CHARS && CURT_REFUSAL.test(unquoted)) {
    return unquoted;
  }

  return null;
}

/** Sender address, lowercased, with any display name removed. */
export function senderAddress(from: string): string {
  const angled = /<([^>]+)>/.exec(from);
  return (angled ? angled[1] : from).trim().toLowerCase();
}

export function classifyInbound(message: InboundMessage): ClassificationResult {
  // 1. Bounces first. They quote the original message, so a later rule would
  //    happily read one as a reply from the prospect.
  if (looksLikeBounce(message)) {
    const dsn = parseDsn(message.raw ?? message.text);
    const suppress = dsn.hard ? (dsn.recipient ?? undefined) : undefined;
    return {
      classification: "bounce",
      reason: dsn.status
        ? `Delivery status ${dsn.status}`
        : "Delivery notification with no parsable status",
      dsn,
      suppress,
    };
  }

  // 2. Auto-replies before unsubscribe, because a vacation notice or a ticket
  //    footer routinely carries the word "unsubscribe".
  if (looksLikeAutoReply(message)) {
    return {
      classification: "auto_reply",
      reason: "Automated response. The sequence continues.",
    };
  }

  // 3. An explicit opt-out from a human.
  const phrase = findUnsubscribeIntent(message);
  if (phrase) {
    return {
      classification: "unsubscribe",
      reason: `Opt-out request: "${phrase}"`,
      suppress: senderAddress(message.headers.from),
    };
  }

  // 4. Anything left from a human stops the sequence.
  return {
    classification: "reply",
    reason: "Human reply",
  };
}
